import React, { useEffect, useState, useCallback } from 'react';
import { supabase } from '../../sbclient/supabaseClient';
import { 
  Calendar, Clock, Search, Zap, 
  CheckCircle, MapPin, Timer, Info,
  ChevronLeft, ChevronRight, X, Loader2
} from 'lucide-react';
import toast from 'react-hot-toast';

// Utility to load Razorpay SDK dynamically
const loadRazorpayScript = () => {
  return new Promise((resolve) => {
    const script = document.createElement("script");
    script.src = "https://checkout.razorpay.com/v1/checkout.js";
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
};

const EventList = () => {
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  
  // Modal State & Animation Trigger
  const [poppedEvent, setPoppedEvent] = useState(null);
  const [isClosing, setIsClosing] = useState(false); 
  
  const [now, setNow] = useState(new Date());

  // NEW: Razorpay Loading State
  const [processingPayment, setProcessingPayment] = useState(false);

  useEffect(() => {
    const ticker = setInterval(() => setNow(new Date()), 60000);
    return () => clearInterval(ticker);
  }, []);

  const fetchEvents = useCallback(async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      const currentIso = now.toISOString();

      const { data: eventData, error: eventError } = await supabase
        .from('events')
        .select('*')
        .gte('reg_end_timestamp', currentIso) 
        .order('date', { ascending: true });

      if (eventError) throw eventError;

      const { data: bookingData } = await supabase.from('bookings').select('event_id, student_email, status');

      const eventsWithMeta = (eventData || []).map(event => {
        const eventBookings = bookingData?.filter(b => b.event_id === event.id) || [];
        const startTime = new Date(event.reg_start_timestamp);
        
        const isBooked = user && eventBookings.some(b => b.student_email === user.email && (b.status === 'confirmed' || b.status === 'verified'));
        const isPending = user && eventBookings.some(b => b.student_email === user.email && b.status === 'pending');

        return {
          ...event,
          isSoldOut: event.ticket_limit && eventBookings.length >= event.ticket_limit,
          isBooked: isBooked,
          isPending: isPending,
          isOpen: now >= startTime
        };
      });

      setEvents(eventsWithMeta);
    } catch (error) {
      toast.error("Discovery Failed");
    } finally {
      setLoading(false);
    }
  }, [now]);

  useEffect(() => {
    fetchEvents();
  }, [fetchEvents]);


  // --- NEW: RAZORPAY INTEGRATION ---
  const handleBook = async (e, event) => {
    e.stopPropagation(); 
    
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return toast.error("Login Required");

    if (!event.isOpen) return toast.error("Registration not yet open!");
    if (event.isBooked) return toast.error("Identity already secured!");
    if (event.isSoldOut) return toast.error("Deployment Full: Sold Out!");

    // PAID EVENT LOGIC (RAZORPAY)
    if (event.event_type === 'paid') {
      setProcessingPayment(true);

      try {
        // 1. Load Razorpay Script
        const res = await loadRazorpayScript();
        if (!res) {
          toast.error("Razorpay SDK failed to load. Are you online?");
          setProcessingPayment(false);
          return;
        }

        // 2. Call your backend to create a Razorpay Order ID securely
        // NOTE: You will need a Supabase Edge Function to generate this.
        const PLATFORM_FEE = 10;
        const totalAmount = event.price + PLATFORM_FEE;

        const { data: orderData, error: orderError } = await supabase.functions.invoke('create-razorpay-order', {
          body: { event_id: event.id, amount: totalAmount }
        });

        if (orderError || !orderData) {
          throw new Error("Failed to initialize order with server.");
        }

        // 3. Initialize Razorpay Checkout
        const options = {
          key: process.env.REACT_APP_RAZORPAY_KEY_ID || 'YOUR_RAZORPAY_KEY_ID', // Replace with your Key ID
          amount: orderData.amount, // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
          currency: "INR",
          name: "ActiveArch Events",
          description: `Pass for ${event.title}`,
          order_id: orderData.id, // The order ID generated by your backend
          handler: async function (response) {
            // 4. Success Callback: User successfully paid! Verify & create booking.
            const { error: bookingError } = await supabase.from('bookings').insert([{
              event_id: event.id,
              student_email: user.email,
              status: 'verified', // Directly marking as verified!
              razorpay_payment_id: response.razorpay_payment_id,
              razorpay_order_id: response.razorpay_order_id,
              razorpay_signature: response.razorpay_signature
            }]);

            if (!bookingError) {
              toast.success("Payment Successful! Pass Secured.");
              fetchEvents();
              // Redirect to tickets page
              setTimeout(() => {
                window.location.href = `/student/tickets?autoFlip=true#ticket-${event.id}`;
              }, 1500);
            } else {
              toast.error("Payment received, but ticket generation failed. Contact Admin.");
            }
          },
          prefill: {
            email: user.email,
          },
          theme: {
            color: "#10b981" // Emerald 500 to match your UI
          }
        };

        const paymentObject = new window.Razorpay(options);
        paymentObject.on('payment.failed', function (response) {
          toast.error(`Payment Failed: ${response.error.description}`);
        });
        paymentObject.open();

      } catch (error) {
        console.error(error);
        toast.error("Could not initiate payment. Please try again.");
      } finally {
        setProcessingPayment(false);
      }
      
      return;
    }

    // FREE EVENT LOGIC (Unchanged)
    const { error } = await supabase.from('bookings').insert([{
      event_id: event.id,
      student_email: user.email,
      status: 'confirmed'
    }]);

    if (!error) {
      toast.success("Pass Secured!");
      fetchEvents(); 
    } else {
      toast.error("Booking failed: " + error.message);
    }
  };

  const filteredEvents = events.filter(e => {
    const matchesSearch = e.title.toLowerCase().includes(searchQuery.toLowerCase());
    let matchesStatus = statusFilter === 'all' || (statusFilter === 'available' ? !e.isBooked : e.isBooked);
    return matchesSearch && matchesStatus;
  });

  const closePoppedEvent = () => {
    setIsClosing(true); 
    setTimeout(() => {
      setPoppedEvent(null); 
      setIsClosing(false);  
    }, 400); 
  };

  if (loading) return <div className="h-screen bg-[#0a0f1d] flex items-center justify-center"><Zap className="animate-pulse text-blue-500" size={48}/></div>;

  return (
    <div className="min-h-screen bg-[#0a0f1d] text-white p-4 md:p-6 pb-24 selection:bg-blue-500/30">
      <div className="max-w-7xl mx-auto space-y-12">
        
        <div className="flex flex-col gap-6">
          <div className="bg-[#111827]/90 backdrop-blur-xl p-3 rounded-4xl border border-white/5 shadow-2xl">
            <div className="relative w-full text-left">
              <Search className="absolute left-6 top-9 -translate-y-1/2 text-slate-500" size={20} />
              <input 
                type="text"
                placeholder="SEARCH Events..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-14 pr-6 py-4 bg-[#1f2937]/50 border-none rounded-3xl outline-none text-sm font-black tracking-widest uppercase focus:ring-2 focus:ring-emerald-500/50 transition-all"
              />
            </div>
          </div>

          <div className="flex justify-center w-full">
            <div className="bg-white rounded-2xl px-20 py-3.5 shadow-[0_10px_40px_rgba(0,0,0,0.4)] border border-white/10 flex items-center justify-center">
              <img src="/adypu logo.png" alt="ADYPU Logo" className="h-10 md:h-12 object-contain" />
            </div>
          </div>
          
          <div className="flex items-center gap-2 p-1.5 bg-[#111827] border border-white/5 rounded-2xl w-fit self-center md:self-start">
            {['all', 'available', 'Booked'].map(s => (
              <button key={s} onClick={() => setStatusFilter(s)} className={`px-5 py-2.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${statusFilter === s ? 'bg-blue-600 text-white shadow-lg' : 'text-slate-500 hover:text-white'}`}>{s}</button>
            ))}
          </div>
        </div>

        <section className="space-y-8 text-left">
          <h2 className="text-2xl font-black uppercase italic flex items-center gap-3"><Zap className="text-yellow-500 fill-yellow-500" size={24}/> Registrations Open</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {filteredEvents.map(event => (
              <FlipCard 
                key={event.id} 
                event={event} 
                onBook={handleBook}
                onFlip={() => setPoppedEvent(event)} 
              />
            ))}
          </div>
        </section>
      </div>

      {/* --- RESPONSIVE FLIP & POP-OUT MODAL --- */}
      {poppedEvent && (
          <div 
            className="fixed inset-0 z-150 flex items-center justify-center p-3 sm:p-6 bg-black/80 backdrop-blur-md" 
            onClick={closePoppedEvent}
          >
          <div 
            className={`relative w-[95%] sm:w-full max-w-2xl max-h-[90vh] bg-[#1e293b] rounded-3xl md:rounded-[2.5rem] border-2 border-blue-500/40 shadow-[0_0_50px_rgba(59,130,246,0.3)] p-5 md:p-10 flex flex-col overflow-hidden ${isClosing ? 'animate-flip-pop-out' : 'animate-flip-pop'}`}
            onClick={(e) => e.stopPropagation()}
          >
            <button 
              onClick={closePoppedEvent} 
              className="absolute top-4 right-4 md:top-5 md:right-5 p-2 text-slate-400 hover:text-white rounded-full hover:bg-white/5 transition-colors z-10"
            >
              <X size={20} className="md:w-6 md:h-6" />
            </button>

            <h4 className="text-[11px] md:text-[14px] font-black text-blue-400 uppercase tracking-widest mb-4 md:mb-5 flex items-center gap-2 border-b border-white/10 pb-3 md:pb-4 pr-8">
              <Zap size={14} className="md:w-4 md:h-4" /> Event Specification
            </h4>
            
            <div className="grow overflow-y-auto custom-scrollbar pr-2 md:pr-3">
              <div className="event-description text-slate-300 text-[13px] md:text-[16px] leading-relaxed md:leading-[1.8] font-normal text-left tracking-wide"
              dangerouslySetInnerHTML={{ __html: poppedEvent.description }}
              />
            </div>
            
            <div className="mt-4 md:mt-6 pt-4 md:pt-5 border-t border-white/5 flex justify-center shrink-0">
               <button onClick={closePoppedEvent} className="px-6 py-2.5 md:px-8 md:py-3 bg-[#0f172a] hover:bg-blue-600 text-white rounded-lg md:rounded-xl font-bold uppercase tracking-widest text-[9px] md:text-[10px] transition-all border border-white/10 hover:border-blue-500 shadow-lg active:scale-95">
                  Close
               </button>
            </div>
          </div>
        </div>
      )}

      {/* Loading Overlay while talking to Razorpay backend */}
      {processingPayment && (
        <div className="fixed inset-0 z-200 flex flex-col items-center justify-center p-4 bg-black/80 backdrop-blur-md">
           <Loader2 className="animate-spin text-emerald-500 mb-4" size={48} />
           <p className="text-white font-bold tracking-widest uppercase text-sm">Initiating Secure Checkout...</p>
        </div>
      )}

      <style>{`
        @keyframes flipPop {
          0% { transform: perspective(2000px) scale(0.8) rotateY(-90deg); opacity: 0; }
          100% { transform: perspective(2000px) scale(1) rotateY(0deg); opacity: 1; }
        }
        @keyframes flipPopOut {
          0% { transform: perspective(2000px) scale(1) rotateY(0deg); opacity: 1; }
          100% { transform: perspective(2000px) scale(0.8) rotateY(90deg); opacity: 0; }
        }
        
        .animate-flip-pop {
          animation: flipPop 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards;
        }
        .animate-flip-pop-out {
          animation: flipPopOut 0.4s cubic-bezier(0.6, -0.28, 0.735, 0.045) forwards;
        }

        .line-clamp-2 { display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; } 
        
        .custom-scrollbar::-webkit-scrollbar { width: 4px; } 
        .custom-scrollbar::-webkit-scrollbar-track { background: rgba(255, 255, 255, 0.05); border-radius: 10px; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(59, 130, 246, 0.6); border-radius: 10px; }

        .event-description p { margin-bottom: 1rem; }
        .event-description p:last-child { margin-bottom: 0; }
        .event-description strong, .event-description b { font-weight: 700; color: #ffffff; }
        .event-description em, .event-description i { font-style: italic; }
        .event-description ul { list-style-type: disc; padding-left: 1.5rem; margin-bottom: 1rem; }
        .event-description ol { list-style-type: decimal; padding-left: 1.5rem; margin-bottom: 1rem; }
        .event-description h1, .event-description h2, .event-description h3 { font-weight: 800; color: #ffffff; margin-top: 1.5rem; margin-bottom: 0.5rem; line-height: 1.2; }
        .event-description a { color: #60a5fa; text-decoration: underline; transition: color 0.2s; }
        .event-description a:hover { color: #3b82f6; }
      `}</style>
    </div>
  );
};

const FlipCard = ({ event, onBook, onFlip }) => {
  const [currentImgIndex, setCurrentImgIndex] = useState(0);

  const defaultImages = [
    "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800",
    "https://images.unsplash.com/photo-1551818255-e6e10975bc17?auto=format&fit=crop&q=80&w=800",
    "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&q=80&w=800"
  ];
  
  const images = Array.isArray(event.images) && event.images.length > 0 ? event.images : defaultImages;

  const nextImage = (e) => {
    e.stopPropagation(); 
    setCurrentImgIndex((prev) => (prev === images.length - 1 ? 0 : prev + 1));
  };

  const prevImage = (e) => {
    e.stopPropagation(); 
    setCurrentImgIndex((prev) => (prev === 0 ? images.length - 1 : prev - 1));
  };

  const glowClass = event.isBooked 
    ? 'border-green-500 shadow-[0_0_25px_rgba(34,197,94,0.25)]' 
    : event.isPending 
    ? 'border-yellow-500 shadow-[0_0_25px_rgba(234,179,8,0.25)]'
    : 'border-blue-500/40 hover:border-blue-500 hover:shadow-[0_0_30px_rgba(59,130,246,0.3)] shadow-[0_0_20px_rgba(59,130,246,0.15)]';

  const getTimeRemaining = () => {
    const diff = new Date(event.reg_start_timestamp) - new Date();
    if (diff <= 0) return "Opening...";
    const hours = Math.floor(diff / 3600000);
    const mins = Math.floor((diff % 3600000) / 60000);
    return hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;
  };

  const formatDateTime = (isoString) => {
    if (!isoString) return 'TBA';
    const date = new Date(isoString);
    return date.toLocaleDateString('en-US', { month: 'short', day: '2-digit' }) + ' @ ' + 
           date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
  };

  const formatEventTime = (timeStr) => {
    if (!timeStr) return '';
    if (timeStr.toLowerCase().includes('m')) return timeStr; 
    const [hours, minutes] = timeStr.split(':');
    let h = parseInt(hours, 10);
    const ampm = h >= 12 ? 'PM' : 'AM';
    h = h % 12 || 12;
    const formattedH = h < 10 ? `0${h}` : h;
    return `${formattedH}:${minutes} ${ampm}`;
  };

  return (
    <div className="h-142.5 w-full group">
      
      <div 
        onClick={onFlip} 
        className={`relative w-full h-full bg-[#0f172a] rounded-[2.5rem] border-2 p-6 md:p-7 flex flex-col justify-start cursor-pointer transition-all duration-500 ${glowClass} hover:-translate-y-2`}
      >
        <div className="flex justify-between items-start mb-4 shrink-0">
          <span className="px-3 py-1 rounded-full text-[8px] font-black uppercase tracking-widest bg-blue-500/10 text-blue-400 border border-blue-500/20 truncate max-w-45">{event.school}</span>
          <div className="flex items-center gap-2">
             <Info size={14} className="text-slate-500 hover:text-blue-400 transition-colors"/> 
             {event.isBooked ? (
               <div className="flex items-center gap-1 text-green-500 font-black text-[8px] uppercase shrink-0"><CheckCircle size={12}/> Verified</div>
             ) : event.isPending ? (
               <div className="flex items-center gap-1 text-yellow-500 font-black text-[8px] uppercase shrink-0 animate-pulse"><Timer size={12}/> Pending</div>
             ) : !event.isOpen && (
               <div className="flex items-center gap-1.5 text-blue-400 font-black text-[8px] uppercase bg-blue-500/10 px-3 py-1 rounded-full shrink-0">
                 <Timer size={12}/> {getTimeRemaining()}
               </div>
             )}
          </div>
        </div>

        <div className="relative w-full h-40 rounded-2xl overflow-hidden shrink-0 mb-4 group/slider border border-white/10 shadow-inner bg-slate-900">
          <img 
            src={images[currentImgIndex]} 
            alt="Event Visualization" 
            className="w-full h-full object-cover transition-opacity duration-500 ease-in-out"
          />
          <div className="absolute inset-0 bg-linear-to-t from-[#0f172a] via-transparent to-transparent opacity-80 pointer-events-none"></div>
          <div className="absolute top-2 right-2 bg-black/60 backdrop-blur-md px-2 py-1 rounded-lg text-[8px] font-black text-white uppercase tracking-widest">
            {currentImgIndex + 1} / {images.length} IMAGES
          </div>

          {images.length > 1 && (
            <>
              <button onClick={prevImage} className="absolute left-2 top-1/2 -translate-y-1/2 bg-black/50 hover:bg-blue-600 text-white p-1.5 rounded-full opacity-0 group-hover/slider:opacity-100 transition-all backdrop-blur-sm">
                <ChevronLeft size={16} />
              </button>
              <button onClick={nextImage} className="absolute right-2 top-1/2 -translate-y-1/2 bg-black/50 hover:bg-blue-600 text-white p-1.5 rounded-full opacity-0 group-hover/slider:opacity-100 transition-all backdrop-blur-sm">
                <ChevronRight size={16} />
              </button>
            </>
          )}

          <div className="absolute bottom-3 left-1/2 -translate-x-1/2 flex gap-1.5 z-10">
            {images.map((_, idx) => (
              <div key={idx} className={`h-1.5 rounded-full transition-all duration-300 ${idx === currentImgIndex ? 'bg-blue-500 w-4' : 'bg-white/40 w-1.5'}`} />
            ))}
          </div>
        </div>

        <div className="grow flex flex-col justify-start text-left gap-3">
          <h3 className={`text-2xl font-black uppercase italic leading-[0.9] line-clamp-2 overflow-hidden shrink-0 ${event.isBooked ? 'text-green-500' : event.isPending ? 'text-yellow-500' : 'text-white'}`}>
            {event.title}
          </h3>
          
          <div className="space-y-1 shrink-0">
            <div className="flex items-center gap-2 text-slate-400 text-[9px] font-bold uppercase">
              <Calendar size={12} className="text-blue-500"/> {event.date}
            </div>
            <div className="flex items-center gap-2 text-slate-400 text-[9px] font-bold uppercase">
              <Clock size={12} className="text-blue-500"/> 
              {formatEventTime(event.start_time)} - {formatEventTime(event.end_time)}
            </div>
            <div className="flex items-center gap-2 text-slate-400 text-[9px] font-bold uppercase truncate max-w-[95%]">
              <MapPin size={12} className="text-blue-500"/> {event.venue}
            </div>
          </div>

          <div className="flex items-center gap-2 text-blue-500 text-[13px] font-black uppercase tracking-widest justify-center bg-center text-center">
              {event.event_type === 'paid' && <span className="text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">Entry Fee ₹{event.price}</span>}
          </div>

          <div className="pt-3 border-t border-slate-700/50 space-y-2 shrink-0">
            <div className="flex items-center gap-2 text-blue-500 text-[13px] font-black uppercase tracking-widest justify-between bg-center text-center">
              <span className="flex items-center gap-2"><Timer size={12}/> Registration Window</span>
            </div>
            <div className="flex flex-col gap-1.5 text-[9px] font-bold text-slate-400 uppercase tracking-widest">
              <div className="flex justify-between bg-[#111827] px-3 py-2 rounded-lg border border-white/5">
                <span className="text-slate-500">Opens</span>
                <span className="text-white">{formatDateTime(event.reg_start_timestamp)}</span>
              </div>
              <div className="flex justify-between bg-[#111827] px-3 py-2 rounded-lg border border-white/5">
                <span className="text-slate-500">Closes</span>
                <span className="text-white">{formatDateTime(event.reg_end_timestamp)}</span>
              </div>
            </div>
          </div>

          <button 
            disabled={event.isBooked || event.isSoldOut || !event.isOpen || event.isPending}
            onClick={(e) => { e.stopPropagation(); onBook(e, event); }}
            className={`w-full py-3.5 mt-auto rounded-2xl font-black uppercase text-[9px] transition-all tracking-widest shrink-0 ${
              event.isBooked ? 'bg-green-600/20 text-green-500 border border-green-500/30' : 
              event.isPending ? 'bg-yellow-600/20 text-yellow-500 border border-yellow-500/30' :
              !event.isOpen ? 'bg-slate-900 text-slate-700 border border-white/5' :
              event.event_type === 'paid' ? 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-lg active:scale-95' :
              'bg-blue-600 hover:bg-blue-700 text-white shadow-lg active:scale-95'
            }`}
          >
            {event.isBooked ? "Pass Secured" : event.isPending ? "Awaiting Verification" : !event.isOpen ? "Opening Soon" : "Book Your Pass"}
          </button>
        </div>
      </div>
    </div>
  );
};

export default EventList;